version: "3.9"

services:
  db:
    image: mongo:5.0-focal
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DEVBOX_MONGO50_DB_USER:-root}
      MONGO_INITDB_ROOT_PASSWORD: ${DEVBOX_MONGO50_DB_PASSWORD:-password}
    volumes:
      - mongo50_db_data:/data/db
    networks:
      - mongo50_network_local
    hostname: db.mongo50.devbox.local
    ports:
      - ${DEVBOX_MONGO50_DB_EXPORT_PORT:-28017}:27017
    healthcheck:
      test: ["CMD", "mongo", "--quiet", "127.0.0.1/test", "--eval", "'quit(db.runCommand({ ping: 1 }).ok ? 0 : 2)'"]
      start_period: 10s
      interval: 3s
      timeout: 1s
      retries: 20
  mongo-express:
    image: mongo-express:0.54
    depends_on:
      db:
        condition: service_healthy
    environment:
      ME_CONFIG_MONGODB_SERVER: db.mongo50.devbox.local
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${DEVBOX_MONGO50_DB_USER:-root}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${DEVBOX_MONGO50_DB_PASSWORD:-password}
    networks:
      - mongo50_network_local
    hostname: mongo-express.mongo50.devbox.local
    ports:
      - ${DEVBOX_MONGO50_EXPRESS_EXPORT_PORT:-28018}:8081
    healthcheck:
      test: ["CMD", "nc", "-vz", "127.0.0.1", "8081"]
      interval: 3s
      timeout: 1s
      retries: 20
  dbgate:
    image: dbgate/dbgate:alpine
    depends_on:
      db:
        condition: service_healthy
    environment:
      CONNECTIONS: mongo1
      ENGINE_mongo1: mongo@dbgate-plugin-mongo
      LABEL_mongo1: db.mongo50.devbox.local
      SERVER_mongo1: db.mongo50.devbox.local
      PORT_mongo1: 27017
      USER_mongo1: ${DEVBOX_MONGO50_DB_USER:-root}
      PASSWORD_mongo1: ${DEVBOX_MONGO50_DB_PASSWORD:-password}
    networks:
      - mongo50_network_local
    hostname: dbgate.mongo50.devbox.local
    ports:
      - ${DEVBOX_MONGO50_DBGATE_EXPORT_PORT:-28019}:3000
    healthcheck:
      test: ["CMD", "nc", "-vz", "127.0.0.1", "3000"]
      interval: 3s
      timeout: 1s
      retries: 20
  nosqlclient:
    image: mongoclient/mongoclient:4.0.1
    depends_on:
      db:
        condition: service_healthy
    environment:
      MONGOCLIENT_DEFAULT_CONNECTION_URL: mongodb://${DEVBOX_MONGO50_DB_USER:-root}:${DEVBOX_MONGO50_DB_PASSWORD:-password}@db.mongo50.devbox.local:27017
    volumes:
      - mongo50_nosqlclient_data:/data/db
    hostname: nosqlclient.mongo50.devbox.local
    networks:
      - mongo50_network_local
    ports:
      - ${DEVBOX_MONGO50_NOSQLCLIENT_EXPORT_PORT:-28020}:3000
    healthcheck:
      test: ["CMD", "curl", "--connect-timeout", "1", "-s", "http://127.0.0.1:3000"]
      interval: 3s
      timeout: 1s
      retries: 20

volumes:
  mongo50_db_data:
  mongo50_nosqlclient_data:

networks:
  mongo50_network_local:
    driver: bridge
