version: "3.9"

services:
  db:
    image: mariadb:11.0
    environment:
      MARIADB_ROOT_PASSWORD: ${DEVBOX_MARIADB110_ROOT_PASSWORD:-password}
    volumes:
      - mariadb110_data:/var/lib/mysql
    networks:
      - mariadb110_network_local
    hostname: db.mariadb110.devbox.local
    ports:
      - ${DEVBOX_MARIADB110_DB_EXPORT_PORT:-15306}:3306
    healthcheck:
      test: /usr/local/bin/healthcheck.sh --su-mysql --connect --innodb_initialized
      start_period: 5s
      interval: 3s
      timeout: 1s
      retries: 20
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:5
    depends_on:
      db:
        condition: service_healthy
    environment:
      PMA_HOST: db.mariadb110.devbox.local
      PMA_USER: root
      PMA_PASSWORD: ${DEVBOX_MARIADB110_ROOT_PASSWORD:-password}
    networks:
      - mariadb110_network_local
    hostname: phpmyadmin.mariadb110.devbox.local
    ports:
      - ${DEVBOX_MARIADB110_PMA_EXPORT_PORT:-15307}:80
    healthcheck:
      test: ["CMD", "curl", "--connect-timeout", "1", "-s", "http://127.0.0.1"]
      interval: 3s
      timeout: 1s
      retries: 20
  adminer:
    image: adminer:4
    depends_on:
      db:
        condition: service_healthy
    environment:
      ADMINER_DEFAULT_SERVER: db.mariadb110.devbox.local
    networks:
      - mariadb110_network_local
    hostname: adminer.mariadb110.devbox.local
    ports:
      - ${DEVBOX_MARIADB110_ADMINER_EXPORT_PORT:-15308}:8080
    healthcheck:
      test: ["CMD", "curl", "--connect-timeout", "1", "-s", "http://127.0.0.1:8080"]
      interval: 3s
      timeout: 1s
      retries: 20
  dbgate:
    image: dbgate/dbgate:alpine
    depends_on:
      db:
        condition: service_healthy
    environment:
      CONNECTIONS: mariadb1
      LABEL_mariadb1: db.mariadb110.devbox.local
      SERVER_mariadb1: db.mariadb110.devbox.local
      USER_mariadb1: root
      PASSWORD_mariadb1: ${DEVBOX_MARIADB110_ROOT_PASSWORD:-password}
      PORT_mariadb1: 3306
      ENGINE_mariadb1: mysql@dbgate-plugin-mysql
    networks:
      - mariadb110_network_local
    hostname: dbgate.mariadb110.devbox.local
    ports:
      - ${DEVBOX_MARIADB110_DBGATE_EXPORT_PORT:-15309}:3000
    healthcheck:
      test: ["CMD", "nc", "-vz", "127.0.0.1", "3000"]
      interval: 3s
      timeout: 1s
      retries: 20

volumes:
  mariadb110_data:

networks:
  mariadb110_network_local:
    driver: bridge
